config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/new', to: 'questions#new'
  get '/quiz', to: 'quiz_mode#quiz'
  get '/new_user', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/check_quiz', to: 'quiz_mode#check_quiz'
  post '/new', to: 'questions#create'
  post '/signup',  to: 'users#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :questions
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	validates :content, presence: true
	validates :answer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
  	@question = Question.find(params[:id])
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = Question.new(question_params)
  	if @question.save
  		redirect_to current_user
  	else
  		render 'new'
  	end
  end

  private

  	def question_params
  		params.require(:question).permit(:content, :answer)
  	end

end

app/controllers/quiz_mode_controller.rb
class QuizModeController < ApplicationController
  
  def quiz
    get_new_question
    render 'show'
  end

  def show
  end

  def check_quiz
  	@answer = Question.new(quiz_params)
  	@question = Question.find(params[:id])
  	if @answer.answer.downcase.squish == @question.answer.downcase.squish || (NumbersInWords.in_numbers(@answer.answer)).to_s.downcase.squish == @question.answer.downcase.squish
      flash[:success] = "Correct!"
      update_score
      redirect_to quiz_path
  	else
      flash[:warning] = "Incorrect! The correct answer is " + @question.answer + "."
      flash[:danger] = "Your final score is #{session[:score]}."
      delete_score
  		redirect_to current_user
  	end
  end

  def get_new_question
    @question = Question.all.to_a.shuffle.first
    @answer = Question.new
    @answer.content = @question.content
    @answer.id = @question.id
  end
  
  private

  	def quiz_params
  		params.permit(:answer, :id)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    create_score
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Quiz Master!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_mode_helper.rb
module QuizModeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def create_score
    session[:score] = 0
  end
  
  def update_score
     session[:score] += 1
  end

  def delete_score
    session.delete(:score)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "Quiz Master", current_user, id: "logo" %>
    <% else %>
      <%= link_to "Quiz Master", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      	<% if logged_in? %>
      	<li><%= link_to "Log out", logout_path, method: :delete %>
      	<% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz Master Home</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/new.html.erb
<h1>Make new question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question) do |f| %>
      <%= f.label :content %>
      <%= f.text_area :content, :cols => "10", :rows => "7" %>

      <%= f.label :answer %>
      <%= f.text_area :answer, :cols => "10", :rows => "3" %>

      <%= f.submit "Create question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<%= @question.content %>
<%= @question.answer %>

app/views/quiz_mode/new_quiz.html.erb
<!-- Quiz Home -->

<h1>QuizMode#quiz</h1>
<p>Find me in app/views/quiz_mode/quiz.html.erb</p>

<%= link_to "Start new quiz", quiz_path %>

app/views/quiz_mode/quiz.html.erb
<!-- Quiz Home -->

<h1>QuizMode#quiz</h1>
<p>Find me in app/views/quiz_mode/quiz.html.erb</p>

<%= link_to "New quiz", new_quiz_path %>

app/views/quiz_mode/show.html.erb
<!-- Answer Quiz -->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for(@answer, url: check_quiz_path) do %>
      <h1><%= @answer.content %></h1>
      <%= text_area_tag :answer %>
      <%= hidden_field_tag "id", @answer.id %>
      <%= submit_tag "Answer question", class: "btn btn-lg btn-primary" %>
   <% end %>

   <div id="score">
	  <h3>Score: <%= session[:score] %></h3>
   </div>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Quiz Master</h1>
  <br>
  <%= link_to "Sign up now!", 'new_user', class: "btn btn-lg btn-primary" %>
</div>

<%#= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><center>
   <%= @user.name %>
</center></h1>
<table width=100% height=100%>
	<tr align = "center">
		<td width=50%><%= link_to "Take new quiz", quiz_path, class: "btn btn-lg btn-primary"%></td>
		<td width=50%><%= link_to "Make question", new_path , class: "btn btn-lg btn-primary"%></td>
	</tr>
</table>